name: release-bucketeer-io-docs

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "**/**.md"

env:
  DOCS_DIRECTORY: docs

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Yarn install cache
        uses: c-hive/gha-yarn-cache@v2
        with:
          directory: ${{ env.DOCS_DIRECTORY }}
      - name: Yarn install dependencies
        run: |
          cd ${{ env.DOCS_DIRECTORY }}
          yarn install
      - name: Yarn Build
        run: |
          cd ${{ env.DOCS_DIRECTORY }}
          yarn build
      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          entryPoint: ${{ env.DOCS_DIRECTORY }}
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BUCKETEER_IO }}
          projectId: ${{ secrets.FIREBASE_HOSTING_PROJECT_ID }}
          channelId: live
