name: release-bucketeer-io-docs

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Yarn install cache
        uses: c-hive/gha-yarn-cache@v2
      - name: Yarn install dependencies
        run: |
          yarn install
      - name: Yarn Build
        run: |
          yarn build
      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BUCKETEER_IO }}
          projectId: ${{ secrets.FIREBASE_HOSTING_PROJECT_ID }}
          channelId: live
